# GoReleaser configuration for stave
# See https://goreleaser.com for detailed docs.

version: 2

project_name: stave

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    # Generate completions for each shell into a dedicated folder
    - mkdir -p completions
    - go run . completion bash > completions/stave.bash
    - go run . completion zsh > completions/stave.zsh
    - go run . completion fish > completions/stave.fish

builds:
  - id: stave
    main: .
    binary: stave
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/yaklabco/stave/cmd/stave/version.Version={{ .Version }}
      - -X github.com/yaklabco/stave/cmd/stave/version.Commit={{ .FullCommit }}
      - -X github.com/yaklabco/stave/cmd/stave/version.BuildDate={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - { goos: openbsd, goarch: arm, goarm: 6 }
      - { goos: windows, goarch: arm, goarm: 6 }

archives:
  - id: default
    ids: [stave]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - NOTICE
      # Explicitly map the completions folder into the archive
      - src: completions/*
        strip_parent: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'

brews:
  - name: stave
    repository:
      owner: yaklabco
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: YakLabs
      email: official@yaklab.org
    homepage: "https://github.com/yaklabco/stave"
    description: "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
    license: "Apache 2.0"

    # Because of strip_parent: true, files are in the archive root
    install: |
      bin.install "stave"
      bash_completion.install "stave.bash" => "stave"
      zsh_completion.install "stave.zsh" => "_stave"
      fish_completion.install "stave.fish"

    test: |
      system "#{bin}/stave --version"

release:
  draft: false
  github:
    owner: yaklabco
    name: stave
