# GoReleaser configuration for stave
# See https://goreleaser.com for detailed docs.

version: 2

project_name: stave

env:
  - CGO_ENABLED=0

before:
  hooks:
    # Keep modules tidy before building artifacts
    - go mod tidy
    # Generate completions into a hidden cache folder.
    # This avoids the 'dist' cleanup and prevents parallel race conditions.
    - mkdir -p .build_cache/completions
    - sh -c "go run . completion bash > .build_cache/completions/stave.bash"
    - sh -c "go run . completion zsh > .build_cache/completions/stave.zsh"
    - sh -c "go run . completion fish > .build_cache/completions/stave.fish"

builds:
  - id: stave
    main: .
    binary: stave
    flags:
      - -trimpath
    ldflags:
      # Keep it minimal and safe; no package vars assumed.
      - -s -w
      # Inject version metadata so the binary can print it without shelling out.
      - -X github.com/yaklabco/stave/cmd/stave/version.Version={{ .Version }}
      - -X github.com/yaklabco/stave/cmd/stave/version.Commit={{ .FullCommit }}
      - -X github.com/yaklabco/stave/cmd/stave/version.BuildDate={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - { goos: openbsd, goarch: arm, goarm: 6 }
      - { goos: windows, goarch: arm, goarm: 6 }

archives:
  - id: default
    ids: [stave]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - NOTICE
      # Map the completions from our cache into a 'completions' folder in the archive
      - src: .build_cache/completions/*
        dst: completions
        strip_parent: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'

brews:
  - name: stave
    repository:
      owner: yaklabco
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: YakLabs
      email: official@yaklab.org
    homepage: "https://github.com/yaklabco/stave"
    description: "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
    license: "Apache-2.0"

    # Installation logic for the binary and completions
    # We point to the 'completions' folder created in the archive step above
    install: |
      bin.install "stave"
      bash_completion.install "completions/stave.bash" => "stave"
      zsh_completion.install "completions/stave.zsh" => "_stave"
      fish_completion.install "completions/stave.fish"

    # Useful information displayed after 'brew install'
    caveats: |
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"

    test: |
      system "#{bin}/stave --version"

release:
  draft: false
  github:
    owner: yaklabco
    name: stave
