// Code generated by "stringer -type=Color"; DO NOT EDIT.

package st

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Black-0]
	_ = x[Red-1]
	_ = x[Green-2]
	_ = x[Yellow-3]
	_ = x[Blue-4]
	_ = x[Staventa-5]
	_ = x[Cyan-6]
	_ = x[White-7]
	_ = x[BrightBlack-8]
	_ = x[BrightRed-9]
	_ = x[BrightGreen-10]
	_ = x[BrightYellow-11]
	_ = x[BrightBlue-12]
	_ = x[BrightStaventa-13]
	_ = x[BrightCyan-14]
	_ = x[BrightWhite-15]
}

const _Color_name = "BlackRedGreenYellowBlueStaventaCyanWhiteBrightBlackBrightRedBrightGreenBrightYellowBrightBlueBrightStaventaBrightCyanBrightWhite"

var _Color_index = [...]uint8{0, 5, 8, 13, 19, 23, 31, 35, 40, 51, 60, 71, 83, 93, 107, 117, 128}

func (i Color) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Color_index)-1 {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[idx]:_Color_index[idx+1]]
}
